version: '3.2'
services:
  geth:
    image: "matterlabs/geth:latest"
    logging:
        driver: none 
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - type: bind
        source: ./volumes/geth
        target: /var/lib/geth/data